SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-015.
PARAMETERS:P_WERKS TYPE T001W-WERKS OBLIGATORY MEMORY ID WRK.
SELECT-OPTIONS:
                S_BUDAT FOR MATDOC-BUDAT OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.