*&---------------------------------------------------------------------*
*& Include          #####_TOP
*&---------------------------------------------------------------------*
*& Tables
TABLES: AUFK, MATDOC,ZPDNAC.
*& Constants
CONSTANTS: C_INPLACE        TYPE C VALUE 'X',
           C_EXCEL(80)      VALUE 'Excel.Sheet',
           C_DOC_CLASSNAME  TYPE SBDST_CLASSNAME  VALUE 'SOFFICEINTEGRATION',
           C_DOC_CLASSTYPE  TYPE SBDST_CLASSTYPE  VALUE 'OT',
           C_DOC_OBJECT_KEY TYPE SBDST_OBJECT_KEY VALUE 'SOFFICEINTEGRATION',
           GC_EDIT_COLS_AC  TYPE STRING VALUE  '3-4-5-6-7-8-9-10-11-12'.

*& Ranges declarations
RANGES: GT_MATNR FOR MARA-MATNR,
        GT_AUART FOR AUFK-AUART.

*& Field symbols
FIELD-SYMBOLS: <FS>    TYPE STANDARD TABLE,
               <FL>    TYPE ANY,
               <FIELD> TYPE ANY.

*& Types declaration
TYPES: BEGIN OF TY_EDIT_COL,
         COL(2) TYPE N,
       END OF TY_EDIT_COL,
       BEGIN OF TY_TAB_BORDERS,
         CODE_ZONE TYPE CHAR35,
         TABNAME   TYPE TYPENAME,
         STRUCTURE TYPE TYPENAME,
         TOP       TYPE I,
         LEFT      TYPE I,
         ROWS      TYPE I,
         COLS      TYPE I,
       END OF TY_TAB_BORDERS,
       BEGIN OF TY_PATTERN,
         PATTERN TYPE CHAR30,
       END OF TY_PATTERN,
       BEGIN OF TY_MAPPING_TRAINS,
         OLD_TRAIN TYPE CHAR40,
         NEW_TRAIN TYPE CHAR40.
TYPES: END OF TY_MAPPING_TRAINS.

TYPES: BEGIN OF TY_OUT_ORDERS,
         MBLNR TYPE AUFM-MBLNR,
         MJAHR TYPE AUFM-MJAHR,
         ZEILE TYPE AUFM-ZEILE,
         MATNR TYPE AUFM-MATNR,
         AUFNR TYPE AUFM-AUFNR,
         TRAIN TYPE ZPDNTRAIN-TRAIN,
         ARBPL TYPE CRHD-ARBPL,
         WERKS TYPE AUFM-WERKS,
         BUDAT TYPE AUFM-BUDAT,
         VERID TYPE AFPO-VERID,
         BWART TYPE AUFM-BWART,
         AUART TYPE AUFK-AUART,
         ERFMG TYPE AUFM-ERFMG,
         ERFME TYPE AUFM-ERFME,
         SHKZG TYPE AUFM-SHKZG.
TYPES:END OF TY_OUT_ORDERS,
TT_OUT_ORDERS TYPE TABLE OF  TY_OUT_ORDERS.

TYPES: BEGIN OF TY_ORDERS,
         TRAIN  TYPE CHAR03,
         AUFNR  TYPE AUFNR,
         ARBPL  TYPE CRHD-ARBPL,
         STATUS TYPE CHAR10.
TYPES: END OF TY_ORDERS,
TT_ORDERS TYPE TABLE OF TY_ORDERS.

TYPES: BEGIN OF TY_BORDER,
         VAL TYPE CHAR03,
       END OF TY_BORDER.

DATA: GT_ORDERS   TYPE TABLE OF TY_ORDERS.
DATA: GT_OUT_ORDERS TYPE TABLE OF TY_OUT_ORDERS.

TYPES: TT_ALV1_LINE1 TYPE STANDARD TABLE OF ZPDND002MT_ALV1.
DATA: GT_ALV1_LINE1 TYPE TT_ALV1_LINE1.
TYPES: TT_ALV1_LINE2 TYPE STANDARD TABLE OF ZPDND002MT_ALV2.
DATA: GT_ALV1_LINE2 TYPE TT_ALV1_LINE2.
TYPES: TT_ALV1_LINE3 TYPE STANDARD TABLE OF ZPDND002MT_ALV3.
DATA: GT_ALV1_LINE3 TYPE TT_ALV1_LINE3.

TYPES: BEGIN OF TY_ZPDND002MT_ALV1,
         TAB1 LIKE GT_ALV1_LINE1,
         TAB2 LIKE GT_ALV1_LINE2,
         TAB3 LIKE GT_ALV1_LINE3.
TYPES: END OF TY_ZPDND002MT_ALV1.


**$-- Declaration for Global Variable .
DATA :GV_QTY_FG              TYPE MENGE_D,
      GV_DATE                TYPE SY-DATUM,
      GV_COST_CENTER         TYPE CHAR10,
      GV_KOSTL_AC            TYPE KOSTL,
      GV_UNIT                TYPE MEINS,
      GV_OK_CODE             TYPE SY-UCOMM,
      GV_OK_CODE_200         TYPE SY-UCOMM,
      GV_FIRST_SET           TYPE FLAG,
      GV_LINE_COUNT          TYPE I VALUE 2,
      GV_LEFT                TYPE I VALUE 2,
      GV_RETCODE             TYPE SOI_RET_STRING,
      GV_DATE_AC             TYPE SY-DATUM,
      GV_DATE_FG             TYPE SY-DATUM,
      GV_DECIMAL_SEP         TYPE C,
      GV_MATNR_GN            TYPE ZPDND002MT_ALV1-MATNR,
      GS_PDNAC_TYPE_3        TYPE ZPDNAC,
      GS_PDNAC_TYPE_4        TYPE ZPDNAC,
      GS_PDNAC_TYPE_5        TYPE ZPDNAC,
      GV_FIELD               TYPE STRING,
      GV_EXCEL_LANG          TYPE SY-LANGU,
      GV_ERROR               TYPE REF TO I_OI_ERROR,
      GV_PLANT_AUTHORIZED    TYPE ABAP_BOOL,
      GV_POSTING_AUTHORIZED  TYPE ABAP_BOOL,
      V_FIRST                TYPE FLAG,
      V_ROWPOS               TYPE I,
      V_COLPOS               TYPE I,
      HAS                    TYPE I,
      SW1                    TYPE ABAP_BOOL VALUE '',
      GV_TRAINS_HIDE         TYPE STRING,

*& Declarations for class objects
      T_RAN                  TYPE SOI_RANGE_LIST,
      T_CONT                 TYPE SOI_GENERIC_TABLE,
      T_DATA_TABLE           TYPE SBDST_CONTENT,
      T_SOI_CELL_TABLE_FEHLT TYPE SOI_CELL_TABLE,
      T_SOI_CELL_TABLE       TYPE SOI_CELL_TABLE,
      T_RANGES               TYPE SOI_RANGE_ITEM   OCCURS 1 WITH HEADER LINE,
      T_CONTENTS             TYPE SOI_GENERIC_ITEM OCCURS 1 WITH HEADER LINE,
      S_SOI_CELL_ITEM        TYPE SOI_CELL_ITEM,
      GT_RANGES              TYPE SOI_RANGE_LIST,
      LO_TABLE_DESCR         TYPE REF TO CL_ABAP_TABLEDESCR,
      LO_STRUCT_DESCR        TYPE REF TO CL_ABAP_STRUCTDESCR,
      GO_CONTROL             TYPE REF TO I_OI_CONTAINER_CONTROL,
      GO_CONTAINER           TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_DOCUMENT            TYPE REF TO I_OI_DOCUMENT_PROXY,
      V_DUMMYDOCUMENT        TYPE REF TO I_OI_DOCUMENT_PROXY,
      GO_HANDLE              TYPE REF TO I_OI_SPREADSHEET,
      GT_RANGES_LIST         TYPE SOI_FULL_RANGE_TABLE,
      GS_RANGES_LIST         TYPE SOI_FULL_RANGE_ITEM,
      GS_RANGE_AC            TYPE  SOI_FULL_RANGE_ITEM,
      GS_RANGE_TAB4          TYPE  SOI_FULL_RANGE_ITEM,
      GS_RANGE_HEAD          TYPE  SOI_FULL_RANGE_ITEM,
      GV_CHECK_OK            TYPE ABAP_BOOL.

**$-- Declaration for Global tables .
DATA:
  GS_ALV3                 TYPE  ZPDND002MT_ALV1,
  GT_ALV3                 TYPE TABLE OF ZPDND002MT_ALV1,
  GT_ZPDND002MT_ALV1      TYPE TY_ZPDND002MT_ALV1,
  GT_ZPDND002MT_ALV2      TYPE TABLE OF ZPDND002MT_ALV4,
  GT_ZPDND002MT_ALV2_TAUX TYPE TABLE OF ZPDND002MT_ALV4,
  GT_ZPDND002MT_ALV2_AC   TYPE TABLE OF ZPDND002MT_ALV4_C,
  GT_ZPDND002_DIFFUS      TYPE STANDARD TABLE OF ZPDND002_DIFFUS,
  GT_ZPDNAC               TYPE TABLE OF ZPDNAC,
  GT_MATDOC               TYPE TABLE OF MATDOC,
  GT_MAPPING              TYPE TABLE OF TY_MAPPING_TRAINS,
  GT_EXCEL_DATA_1         TYPE STANDARD TABLE OF ZPDND002MT_ALV1,
  GT_EXCEL_DATA_2         TYPE STANDARD TABLE OF ZPDND002MT_ALV2,
  GT_EXCEL_DATA_3         TYPE STANDARD TABLE OF ZPDND002MT_ALV3,
  GT_EXCEL_DATA_4         TYPE STANDARD TABLE OF ZPDND002MT_ALV4_C,
  GT_EXCEL_DATA_4_HEAD    TYPE STANDARD TABLE OF ZPDND002MT_ALV4_C,
  GT_ZPDND002MT_ALV2_C    TYPE TABLE OF ZPDND002MT_ALV4_C,
  GT_EXCEL_DATA_AC        TYPE STANDARD TABLE OF ZPDND002MT_ALV4_C,
  GT_EXCEL_DATA_TOTAL1    TYPE STANDARD TABLE OF ZPDND002MT_ALV1_HEAD,
  GT_EXCEL_DATA_TOTAL2    TYPE STANDARD TABLE OF ZPDND002MT_ALV1_HEAD,
  GT_EXCEL_CHART          TYPE STANDARD TABLE OF ZPDND002MT_CHART,
  GT_TAB_BORDERS          TYPE TABLE OF TY_TAB_BORDERS.