*&---------------------------------------------------------------------*
*& Include          ZIPME010_TOP
*&---------------------------------------------------------------------*
TABLES: BPIN, ZIPME010_EX_RATE, PRPS, CAUFVD.

TYPE-POOLS ABAP.

TYPES: BEGIN OF TY_WBSE_PROJ,
         PROJ  TYPE PROJ-PSPNR,
         WBSE  TYPE PRPS-PSPNR,
         WAERS TYPE PRPS-PWPOS,
       END OF TY_WBSE_PROJ,
       BEGIN OF TY_POPUP_ALV,
         PROJ      TYPE ZIPME010_EX_RATE-PROJ,
         WBSE      TYPE ZIPME010_EX_RATE-WBSE,
         WAERS     TYPE ZIPME010_EX_RATE-WAERS,
         HWAER     TYPE ZIPME010_EX_RATE-HWAER,
         EBELN     TYPE ZIPME010_EX_RATE-EBELN,
         KURSF     TYPE ZIPME010_EX_RATE-KURSF,
         ANDAT     TYPE ZIPME010_EX_RATE-ANDAT,
         ERNAM     TYPE ZIPME010_EX_RATE-ERNAM,
       END OF TY_POPUP_ALV.

DATA: GT_ZIPME010_EX_RATE TYPE TABLE OF ZIPME010_EX_RATE,
      GT_POPUP_EX_RATE    TYPE TABLE OF TY_POPUP_ALV,
      GS_ZIPME010_EX_RATE TYPE ZIPME010_EX_RATE,
      GO_ALV              TYPE REF TO CL_SALV_TABLE,
      LR_FUNCTIONS        TYPE REF TO CL_SALV_FUNCTIONS_LIST,
      LR_COLUMNS          TYPE REF TO CL_SALV_COLUMNS_TABLE,
      LR_COLUMN           TYPE REF TO CL_SALV_COLUMN_TABLE,
      GT_PRPS             TYPE TABLE OF PRPS,
      GV_COUNTER          TYPE I,
      GV_LOC_CURR         TYPE T001-WAERS VALUE 'DZD',
      GV_UPDATE_PROG      TYPE SY-CPROG VALUE 'ZIPMR003',
      GV_UPDATE_TCODE      TYPE SY-TCODE VALUE 'ZIPMR003',
      GV_TEST_PROG      TYPE SY-CPROG VALUE 'ZTEST01'."ZTC_002'.